name: Docker Build & Publish
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_REGISTRY: https://ghcr.io
      DOCKER_IMAGE: ghcr.io/jamvas
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up Docker Buildx"
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: "Prepare"
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
          echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
          echo ::set-output name=version::${GITHUB_RUN_NUMBER}

      - name: "Docker login"
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin

      - name: "Build and publish"
        if: success()
        run: |
          docker buildx build \        
            --platform ${{ steps.prepare.outputs.docker_platform }} \        
            --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \        
            --output type=image,push=true .