name: Docker Build & Publish
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: https://ghcr.io
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Docker login"
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin

      - name: "Build and push Docker image"
        if: success()
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/p0lizeibot:latest
          platforms: linux/arm/v7
          push: true
